name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت پروژه
        uses: actions/checkout@v4

      - name: نصب Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: دادن دسترسی به Gradle
        run: chmod +x gradlew

      - name: ساخت APK
        run: ./gradlew assembleDebug

      - name: ذخیره فایل APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
